highligher: pygments
markdown: kramdown
future: true
gems:
  - jekyll-redirect-from
  - jekyll-mentions

collections:
  projects:
    output: true
    permalink: /projects/:title/

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: "blog"
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "members"
      type: "posts"
    values:
      layout: "person"
